# Generated by Django 5.1.6 on 2025-04-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_weatherdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="id",
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.RenameModel(
            old_name="ModelAuthor",
            new_name="BoardAuthor",
        ),
        migrations.CreateModel(
            name="WeatherBoard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("care", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.boardauthor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ModelPost",
        ),
    ]
