# Generated by Django 5.1.6 on 2025-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_weatherdata_id_alter_weatherdata_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherboard",
            old_name="author",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="weatherboard",
            name="care",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
