# Generated by Django 5.1.6 on 2025-04-08 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_author_weatherboard_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherboard",
            options={"verbose_name": "天气看板", "verbose_name_plural": "天气看板"},
        ),
        migrations.RemoveField(
            model_name="weatherboard",
            name="care",
        ),
        migrations.RemoveField(
            model_name="weatherboard",
            name="owner",
        ),
        migrations.AddField(
            model_name="weatherboard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherboard",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="位置"
            ),
        ),
        migrations.AddField(
            model_name="weatherboard",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
    ]
