# Generated by Django 5.1.6 on 2025-04-08 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_weatherboard_options_remove_weatherboard_care_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="weatherboard",
            options={},
        ),
        migrations.RemoveField(
            model_name="weatherboard",
            name="location",
        ),
        migrations.AlterField(
            model_name="weatherboard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="weatherboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="weatherboard",
            name="locations",
            field=models.ManyToManyField(to="myapp.location"),
        ),
    ]
