# Generated by Django 5.1.6 on 2025-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_location_alter_weatherboard_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherboard",
            name="created_at",
        ),
    ]
